# docker-compose-pg.yml
services:
  postgres:
    image: postgres:17-alpine
    container_name: bookzone_postgres
    restart: always
    environment:
      POSTGRES_DB: bookzone_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5428:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
